<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SlmQueue\Module'                                        => __DIR__ . '/Module.php',
    'SlmQueue\Factory\Exception\RuntimeException'            => __DIR__ . '/src/SlmQueue/Factory/Exception/RuntimeException.php',
    'SlmQueue\Factory\JobPluginManagerFactory'               => __DIR__ . '/src/SlmQueue/Factory/JobPluginManagerFactory.php',
    'SlmQueue\Factory\QueuePluginManagerFactory'             => __DIR__ . '/src/SlmQueue/Factory/QueuePluginManagerFactory.php',
    'SlmQueue\Job\AbstractJob'                               => __DIR__ . '/src/SlmQueue/Job/AbstractJob.php',
    'SlmQueue\Job\Exception\RuntimeException'                => __DIR__ . '/src/SlmQueue/Job/Exception/RuntimeException.php',
    'SlmQueue\Job\JobInterface'                              => __DIR__ . '/src/SlmQueue/Job/JobInterface.php',
    'SlmQueue\Job\JobPluginManager'                          => __DIR__ . '/src/SlmQueue/Job/JobPluginManager.php',
    'SlmQueue\Options\WorkerOptions'                         => __DIR__ . '/src/SlmQueue/Options/WorkerOptions.php',
    'SlmQueue\Queue\AbstractQueue'                           => __DIR__ . '/src/SlmQueue/Queue/AbstractQueue.php',
    'SlmQueue\Queue\Exception\RuntimeException'              => __DIR__ . '/src/SlmQueue/Queue/Exception/RuntimeException.php',
    'SlmQueue\Queue\Exception\UnsupportedOperationException' => __DIR__ . '/src/SlmQueue/Queue/Exception/UnsupportedOperationException.php',
    'SlmQueue\Queue\QueueInterface'                          => __DIR__ . '/src/SlmQueue/Queue/QueueInterface.php',
    'SlmQueue\Queue\QueuePluginManager'                      => __DIR__ . '/src/SlmQueue/Queue/QueuePluginManager.php',
    'SlmQueue\Worker\AbstractWorker'                         => __DIR__ . '/src/SlmQueue/Worker/AbstractWorker.php',
    'SlmQueue\Worker\WorkerInterface'                        => __DIR__ . '/src/SlmQueue/Worker/WorkerInterface.php',
);