<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SlmQueue\Module'                        => __DIR__ . '/Module.php',
    'SlmQueue\Service\BeanstalkInterface'    => __DIR__ . '/src/SlmQueue/Service/BeanstalkInterface.php',
    'SlmQueue\Service\PheanstalkFactory'     => __DIR__ . '/src/SlmQueue/Service/PheanstalkFactory.php',
    'SlmQueue\Service\PheanstalkBridge'      => __DIR__ . '/src/SlmQueue/Service/PheanstalkBridge.php',
    'SlmQueue\Exception\BuryableException'   => __DIR__ . '/src/SlmQueue/Exception/BuryableException.php',
    'SlmQueue\Exception\ReleasableException' => __DIR__ . '/src/SlmQueue/Exception/ReleasableException.php',
    'SlmQueue\Exception\RuntimeException'    => __DIR__ . '/src/SlmQueue/Exception/RuntimeException.php',
    'SlmQueue\Producer\AbstractProducer'     => __DIR__ . '/src/SlmQueue/Producer/AbstractProducer.php',
    'SlmQueue\Producer\ProducerInterface'    => __DIR__ . '/src/SlmQueue/Producer/ProducerInterface.php',
    'SlmQueue\Job\AbstractJob'               => __DIR__ . '/src/SlmQueue/Job/AbstractJob.php',
    'SlmQueue\Job\JobInterface'              => __DIR__ . '/src/SlmQueue/Job/JobInterface.php',
    'SlmQueue\Job\JobManager'                => __DIR__ . '/src/SlmQueue/Job/JobManager.php',
    'SlmQueue\Options\ModuleOptions'         => __DIR__ . '/src/SlmQueue/Options/ModuleOptions.php',
    'SlmQueue\Controller\WorkerController'   => __DIR__ . '/src/SlmQueue/Controller/WorkerController.php',
    'SlmQueue\Controller\Plugin\Queue'       => __DIR__ . '/src/SlmQueue/Controller/Plugin/Queue.php',
);